# The URL the site will be built for
base_url = "https://anser.wtf"

title = "Serena An"
description = "Serena An's personal website"
author = "Serena An"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Turn `:smile:` style shortcodes into emoji
render_emoji = false

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
keywords = "anser, Serena An, MIT, math"
